name: Application health check

on:
  schedule:
    - cron: '* * * 8 0'

jobs:
  simple_healthcheck:
  runs-on: ubuntu-20.04
  steps:
    - name: Check the deployed application
      uses: jtalk/url-health-check-action@v2
      with:
        url: https://pokedex-fullstack-jjsierra.herokuapp.com
        max-attempts: 3
        retry-delay: 5s
        